[workspace]
resolver = "2"
members = ["crates/rewriter", "crates/wisp-wasm", "crates/lj-server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
wisp-core = { git = "https://github.com/lobsterbs/LobsterBrowse", branch = "main" }
wisp-extensions = { git = "https://github.com/lobsterbs/LobsterBrowse", branch = "main" }
wasm-bindgen = "0.2"
bytes = "1"

[profile.release]
opt-level = "z"
lto = true
